### ISSUE TITLE
lack of explanation and error while trying to make

### ISSUE THREAD

**Issue by yerzhik** [JayKothari/i2c_rtdm#1]
i suppose to install the driver i should run make. when i tried running it i got:

> root@beaglebone:/home/machinekit/drivers/i2c_rtdm# make
> make -C /root/embedded_linux/elabs_BBB/beagle-kernel/kernel SUBDIRS=/home/machinekit/drivers/i2c_rtdm modules
> make[1]: *** /root/embedded_linux/elabs_BBB/beagle-kernel/kernel: No such file or directory.  Stop.
> Makefile:7: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by yerzhik** [comment]
I managed to change the directory and everything seemed to compile. Now what? how do I connect driver or enable it?

**Comment by JayKothari** [comment]
This code has been made open source for study propose. It is assumed the engineer using the code knows the background of linux kernel. 

Can you please check you have the generated .ko. And then load the module with linux kernel using insmod or other utility. Once the module is loaded you can check using lsmod. 

Thank you.
